### ISSUE TITLE
init.el 'ess no such file or directory

### ISSUE THREAD

**Issue by rsspdx** [pprevos/r.prevos.net#2]
Using your emacs init file, I get the message:

File error:  Cannot open load file, no such file or directory, ess-site

**Comment by pprevos** [comment]
Hi, Thanks for pointing this out.

Have you installed the ESS package?

Instructions are here: https://ess.r-project.org/Manual/ess.html#Installation-instructions

Peter

**Comment by rsspdx** [comment]
Thank you. I did finally install ess from source, but now I get the warning "Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name olrg.ally.Bus was not provided by any .service files"

Probably unrelated to your init file, and a problem elsewhere in my system. Just trying to get it running. :)

-Richard

===
Richard Sherman
rss.pdx@gmail.com
